export const SampleTasks = [
  {
    id: 1,
    name: "MKV Intranet V2",
    startDate: "04/06/2024",
    endDate: "16/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "medium",
  },
  {
    id: 2,
    name: "Design System",
    startDate: "23/06/2024",
    endDate: "24/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "important",
  },
  {
    id: 3,
    name: "Medical Appointment",
    startDate: "16/06/2024",
    endDate: "18/06/2024",
    assignees: ["/assets/images/user1.jpg", "/assets/images/user2.jpg"],
    priority: "urgent",
  },
  {
    id: 1,
    name: "MKV Intranet V2",
    startDate: "04/06/2024",
    endDate: "16/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "medium",
  },
  {
    id: 2,
    name: "Design System",
    startDate: "23/06/2024",
    endDate: "24/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "important",
  },
  {
    id: 3,
    name: "Medical Appointment",
    startDate: "16/06/2024",
    endDate: "18/06/2024",
    assignees: ["/assets/images/user1.jpg", "/assets/images/user2.jpg"],
    priority: "urgent",
  },
  {
    id: 1,
    name: "MKV Intranet V2",
    startDate: "04/06/2024",
    endDate: "16/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "medium",
  },
  {
    id: 2,
    name: "Design System",
    startDate: "23/06/2024",
    endDate: "24/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "important",
  },
  {
    id: 3,
    name: "Medical Appointment",
    startDate: "16/06/2024",
    endDate: "18/06/2024",
    assignees: ["/assets/images/user1.jpg", "/assets/images/user2.jpg"],
    priority: "urgent",
  },
  {
    id: 1,
    name: "MKV Intranet V2",
    startDate: "04/06/2024",
    endDate: "16/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "medium",
  },
  {
    id: 2,
    name: "Design System",
    startDate: "23/06/2024",
    endDate: "24/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "important",
  },
  {
    id: 3,
    name: "Medical Appointment",
    startDate: "16/06/2024",
    endDate: "18/06/2024",
    assignees: ["/assets/images/user1.jpg", "/assets/images/user2.jpg"],
    priority: "urgent",
  },
  {
    id: 1,
    name: "MKV Intranet V2",
    startDate: "04/06/2024",
    endDate: "16/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "medium",
  },
  {
    id: 2,
    name: "Design System",
    startDate: "23/06/2024",
    endDate: "24/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "important",
  },
  {
    id: 3,
    name: "Medical Appointment",
    startDate: "16/06/2024",
    endDate: "18/06/2024",
    assignees: ["/assets/images/user1.jpg", "/assets/images/user2.jpg"],
    priority: "urgent",
  },
  {
    id: 1,
    name: "MKV Intranet V2",
    startDate: "04/06/2024",
    endDate: "16/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "medium",
  },
  {
    id: 2,
    name: "Design System",
    startDate: "23/06/2024",
    endDate: "24/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "important",
  },
  {
    id: 3,
    name: "Medical Appointment",
    startDate: "16/06/2024",
    endDate: "18/06/2024",
    assignees: ["/assets/images/user1.jpg", "/assets/images/user2.jpg"],
    priority: "urgent",
  },
  {
    id: 1,
    name: "MKV Intranet V2",
    startDate: "04/06/2024",
    endDate: "16/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "medium",
  },
  {
    id: 2,
    name: "Design System",
    startDate: "23/06/2024",
    endDate: "24/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "important",
  },
  {
    id: 3,
    name: "Medical Appointment",
    startDate: "16/06/2024",
    endDate: "18/06/2024",
    assignees: ["/assets/images/user1.jpg", "/assets/images/user2.jpg"],
    priority: "urgent",
  },
  {
    id: 1,
    name: "MKV Intranet V2",
    startDate: "04/06/2024",
    endDate: "16/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "medium",
  },
  {
    id: 2,
    name: "Design System",
    startDate: "23/06/2024",
    endDate: "24/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "important",
  },
  {
    id: 3,
    name: "Medical Appointment",
    startDate: "16/06/2024",
    endDate: "18/06/2024",
    assignees: ["/assets/images/user1.jpg", "/assets/images/user2.jpg"],
    priority: "urgent",
  },
  {
    id: 1,
    name: "MKV Intranet V2",
    startDate: "04/06/2024",
    endDate: "16/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "medium",
  },
  {
    id: 2,
    name: "Design System",
    startDate: "23/06/2024",
    endDate: "24/06/2024",
    assignees: [
      "/assets/images/user1.jpg",
      "/assets/images/user2.jpg",
      "/assets/images/user1.jpg",
    ],
    extraAssignees: 1,
    priority: "important",
  },
  {
    id: 3,
    name: "Medical Appointment",
    startDate: "16/06/2024",
    endDate: "18/06/2024",
    assignees: ["/assets/images/user1.jpg", "/assets/images/user2.jpg"],
    priority: "urgent",
  },
];
